# Load libraries #####
library(dplyr)
library(purrr)

# Read prov file ####

read_prov <- function(prov_json_file) {
    library(rjson)
    json <- fromJSON(file = prov_json_file)
    return(json)
}

# Open file to write #####
file_conn <- "./output2.ttl"

# Create dataframes
df_activity <- bind_rows(lapply(json$activity, data.frame, stringsAsFactors = FALSE)) # not working
df_wasIndformedBy <- bind_rows(lapply(json$wasInformedBy, data.frame, stringsAsFactors = FALSE))
df_wasGeneratedBy <- bind_rows(lapply(json$wasGeneratedBy, data.frame, stringsAsFactors = FALSE))

# Test if it is function, attribution or math ####

check <- function(txt) {
    if (length(grep("\\(", txt, perl = TRUE)) > 0)  {
        return('function')
    }
    if (length(grep("\\<-", txt, perl = TRUE) ) > 0)  {
        return('operation')
    }
    if (length(grep("\\=", txt, perl = TRUE) ) > 0)  {
        return('operation')
    }
    if (length(grep("Console", txt, perl = TRUE) ) > 0)  {
        return('console')
    }
}
# Tesitng <- Apply check function to all activities
lapply(json$activity, function(x){check(x$`rdt:name`)})

# Outputs #####
entities <- json$entity # Get all entities

create_output_df <- function(entities, df_wasGeneratedBy) {
    data_only <- entities[grep('rdt:d', names(entities), perl = TRUE)] # Get only data entities
    #was_generated <- json$wasGeneratedBy #Get generatedBy
    #purrr::map_lgl(.x = was_generated, .f = ~ any(names(data_only) %in% .)) # Test if they are generated by an activity VER AQUI
    df_entity_data <- bind_rows(lapply(data_only, data.frame, stringsAsFactors = FALSE)) # Create DF with only (output) data entities
    df_entity_data$rdt.id <- names(data_only) # Include rdt.id
    df_entity_data$is_output <- df_entity_data$rdt.id %in% df_wasGeneratedBy$prov.entity # Test if each id is generated by an activity VER AQUI

    return(df_entity_data)
}

insert_output <- function(df_entity_data, file_conn) {
    #Write output to ttl file
    for(i in 1:nrow(df_entity_data)){
        if(df_entity_data[i, 'is_output']){
            df_entity_data[i, 'repr'] <- paste0('Output', i)
            cat(paste0('repr:Output', i, ' a p-plan:Variable ; \n rdf:value "', df_entity_data[i, 'rdt.name'], '" ; \n repr:hasType "', df_entity_data[i, 'rdt.type'],'" .'), file = file_conn, append = TRUE, sep = "\n")
        }
    }
    return(df_entity_data)
}

# Activities #####
# TODO create function here
a <- json$activity
all_activities <- a[grep('rdt:p', names(a), perl = TRUE)] # Get all activities. I will test what they do later
# Treating NA values so column has its data type
all_activities <- map(all_activities, function(x) map(x, function(y) ifelse(y == "NA", NA, y)))
df_activity <- bind_rows(lapply(all_activities, data.frame, stringsAsFactors = FALSE)) # List to dataframe
df_activity$rdt.id <- names(all_activities) # To keep de ids from rdt
df_activity$type <- unlist(lapply(df_activity$rdt.name, function(x){check(x)})) # Checking what the activities do


# Activities - Functions #####

create_activity_function <- function(df_activity) {
    df_activity_func <- df_activity[df_activity$type == 'function',] # Get olny functions
    df_activity_func$func_name <- gsub("\\(.*", "", df_activity_func$rdt.name) # Extract function name
    df_activity_func$func_name <- gsub(".*<- ", "", df_activity_func$func_name) # Extract function name
    df_activity_func$func_impl <- lapply(df_activity_func$func_name, function(x) paste(capture.output(eval(parse(text = x))), collapse = "")) # Get function impl.
    #df_activity_func$args <- lapply(df_activity_func$func_name, function(x) as.list(args(x))) # Get function args NOT WORKING

    return(df_activity_func)
}

insert_function <- function(df_activity_func, file_conn) {
    # Write output to ttl file
    df <- unique(df_activity_func[,c(11,12)]) # Get func without repetition
    for(i in 1:nrow(df)){
        df[i, 'repr.Function'] <- paste0('Function', i)
        cat(paste0('repr:Function', i, ' a p-plan:Plan ; \n rdf:value "', df_activity_func[i, 'func_impl'], '" .'), file = file_conn, append = TRUE, sep = "\n")
    }
    df <- merge(df[,c(1,3)], df_activity_func, by = "func_name")
    df <- df %>%
    group_by(func_name) %>%
    mutate(repr.Activation = paste0('Activation', row_number()))
    return(df)
}

# Activities - Function Activation #####

insert_function_activation <- function(df_activity_func, file_conn) {
    apply(df_activity_func, 1, function(x) cat(paste0('repr:', x['repr.Function'], x['repr.Activation'],' repr:FunctionActivation ; \n p-plan:correspondsToStep repr:', x['repr.Function'], ' .'), file = file_conn, append = TRUE, sep = "\n"))
}




