library(getLattes)
data(xmlsLattes)
length(xmlsLattes)
library(dplyr)
getDadosGerais(xmlsLattes[[2]])
lt <- lapply(xmlsLattes, getDadosGerais)
head(bind_rows(lt))
getArtigosPublicados(xmlsLattes[[2]])
lt <- lapply(xmlsLattes, getArtigosPublicados)
head(bind_rows(lt))
